# Shared registration: production Vulkan build and standalone CPU test build.
set(VULKAN_TEST_SRC ${CMAKE_CURRENT_LIST_DIR})
add_executable(test-greedy ${VULKAN_TEST_SRC}/test_greedy.cpp)
add_test(NAME vulkan_greedy COMMAND test-greedy)
add_executable(test-vulkan-policy ${VULKAN_TEST_SRC}/test_policy.cpp)
target_link_libraries(test-vulkan-policy PRIVATE nlohmann_json::nlohmann_json)
add_test(NAME vulkan_policy COMMAND test-vulkan-policy)
add_executable(test-vulkan-prefill ${VULKAN_TEST_SRC}/test_prefill.cpp)
add_test(NAME vulkan_prefill COMMAND test-vulkan-prefill)
add_executable(test-vulkan-startup ${VULKAN_TEST_SRC}/test_startup.cpp)
target_include_directories(test-vulkan-startup PRIVATE ${VULKAN_TEST_SRC})
target_link_libraries(test-vulkan-startup PRIVATE ggml-base)
add_test(NAME vulkan_context_limit COMMAND test-vulkan-startup context)
add_test(NAME vulkan_template_validation COMMAND test-vulkan-startup template)
